version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:<<parameters.ver_major>>.<<parameters.ver_minor>>
    parameters:
      ver_minor:
        type: string
      ver_major:
        type: string
    steps:
      - checkout
      - run: |
          pip install tox
          tox -e py<<parameters.ver_major>><<parameters.ver_minor>>
  deploy-dev:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: |
          poetry install
          poetry run inv release --dev

workflows:
  test:
    jobs:
      - test:
          name: "test-py37"
          ver_major: "3"
          ver_minor: "7"
      - test:
          name: "test-py38"
          ver_major: "3"
          ver_minor: "8"
      - test:
          name: "test-py39"
          ver_major: "3"
          ver_minor: "9"
      - deploy-dev:
          requires:
            - test-py37
            - test-py38
            - test-py39
          filters:
            branches:
              only: development
